go:
  version: 1.23.0
  cgo: false
repository:
  path: github.com/thelande/openmeteo_exporter
build:
  prefix: .
  binaries:
    - name: openmeteo_exporter
  flags: -a -tags 'netgo osusergo static_build'
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  prefix: .
  files:
    - LICENSE
crossbuild:
  platforms:
    - linux
    - darwin
    - windows
